In [2]:
# Import PyTorch
import torch

# Create tensors
a = torch.tensor([[1, 2],
                  [3, 4]])

b = torch.tensor([[5, 6],
                  [7, 8]])

print("Tensor A:\n", a)
print("Tensor B:\n", b)
print("\nAddition:\n", a + b)
print("\nSubtraction:\n", a - b)
print("\nMultiplication:\n", a * b)
print("\nScalar Multiplication:\n", a * 2)
print("\nMatrix Multiplication:\n", torch.matmul(a, b))

Tensor A:
 tensor([[1, 2],
        [3, 4]])
Tensor B:
 tensor([[5, 6],
        [7, 8]])

Addition:
 tensor([[ 6,  8],
        [10, 12]])

Subtraction:
 tensor([[-4, -4],
        [-4, -4]])

Multiplication:
 tensor([[ 5, 12],
        [21, 32]])

Scalar Multiplication:
 tensor([[2, 4],
        [6, 8]])

Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])
